<h2>Exception handling</h2>
<html>
 <head></head>
 <body>
  <p>Okay, at this point, you've probably already had your fair share of all kinds of errors when working on your code. You might even know how to deal with some of them. But what if some parts of your code are not under your direct control (e.g. user input) and present a place for a potential disaster? Also, users aren't always eager to follow the instructions even if they are given, so you have to only rely on yourself. No worries though, Python, as always, has your back. In this topic, we'll learn some tools that can help handle the occurring errors.</p> 
  <p>Imagine a simple calculator, which can only divide numbers, where we ask a user for input of two numbers and then print the result.</p> 
  <pre><code class="language-python">number_one = int(input("Please, enter the first number: "))
number_two = int(input("Please, enter the second number: "))
result = number_one / number_two
print("The result of your division is: ", result)</code></pre> 
  <p>Let's run it:</p> 
  <pre><code class="language-no-highlight">&gt;&gt;&gt; Please, enter the first number: 5
&gt;&gt;&gt; Please, enter the second number:  2
&gt;&gt;&gt; The result of your division is: 2.5</code></pre> 
  <p>Now let's try the impossible:</p> 
  <pre><code class="language-python">&gt;&gt;&gt; Please, enter the first number: 5
&gt;&gt;&gt; Please, enter the second number: 0
Traceback (most recent call last):
File "&lt;input&gt;", line 1, in &lt;module&gt;
File "C:/Users/User/.PyCharm2018.2/config/scratches/scratch_9.py", line 3, in &lt;module&gt;
    result = number_one / number_two
ZeroDivisionError: division by zero</code></pre> 
  <p>Again we encounter this annoying traceback, and our program crashes completely! For preventing this, we need to use <strong>try-except statements</strong> in the place, which can be a possible source of errors. Here is the place where we divide â€” the variable <code class="language-python">result</code>, so let's brace it with try-except blocks:</p> 
  <pre><code class="language-python">number_one = int(input("Please, enter the first number: "))
number_two = int(input("Please, enter the second number: "))
try:
    result = number_one / number_two
except ZeroDivisionError:
    print("We achieve it thanks to except ***You can not divide by zero!!")
else:
    print("The result of your division is: ", result)
finally:
    print("It is done through finally ***Thanks for using our calculator! Come again!")</code></pre> 
  <h5 id="exception-handling-keywords" style="text-align: center;">Exception handling keywords</h5> 
  <p>Here you can see not only <code class="language-python">try</code> and <code class="language-python">except</code> keywords but also <code class="language-python">else</code> and <code class="language-python">finally</code>. The full exception handling block works as follows:</p> 
  <ul> 
   <li>First, Python executes the <code class="language-python">try</code> block: everything between <code class="language-python">try</code> and <code class="language-python">except</code>.</li> 
   <li>If there is <strong>no exception</strong>, the try block is successfully executed and finished.</li> 
   <li>If an exception occurs, the rest of the try block is skipped. After that, Python checks if the type of exception matches the exception specified after the <code class="language-python">except</code> keyword, it executes the except block and continues executing the program after<strong> </strong>the try-except block.</li> 
   <li>If an exception doesn't match the exception named in the<em> </em>except clause, it is called an <strong>unhandled exception,</strong> and the execution of your program stops with a <strong>traceback</strong>.</li> 
   <li>The <strong>else-block</strong> in this situation is only executed if there occurred no exceptions<strong> </strong>in the <code class="language-python">try</code> block as though it was a more familiar if-else statement. It's better to use <code class="language-python">else</code> than adding code to the <code class="language-python">try</code> block because this way you can avoid accidentally catching another exception you haven't initially planned to catch with the <code class="language-python">try</code> block and be aware of it in time. </li> 
   <li>There can also be a <code class="language-python">finally</code><strong> </strong>keyword. A <code class="language-python">finally</code> clause is always executed before leaving the try-except block, whether an exception has occurred or not. </li> 
  </ul> 
  <p style="text-align: center;"><img alt="" height="739" src="https://ucarecdn.com/d796dba0-bdb1-4ae7-941f-de5671a85679/" width="690"></p> 
  <p>So let's try executing our program now!</p> 
  <pre><code class="language-no-highlight">&gt;&gt;&gt; Please, enter the first number: 5
&gt;&gt;&gt; Please, enter the second number: 0
&gt;&gt;&gt; We achieve it thanks to except ***You can not divide by zero!!
&gt;&gt;&gt; It is done through finally ***Thanks for using our calculator! Come again!</code></pre> 
  <p>See? Now our program will be working even if the user makes a mistake and wants to divide by zero.</p> 
  <h5 id="handling-several-exceptions" style="text-align: center;">Handling several exceptions</h5> 
  <p>But what if our user doesn't understand what the "number" is and enters, for example, "one"?</p> 
  <pre><code class="language-python">&gt;&gt;&gt; Please, enter the first number: 5
&gt;&gt;&gt; Please, enter the second number: one
Traceback (most recent call last):
File "&lt;input&gt;", line 1, in &lt;module&gt;
File "C:/Users/User/.PyCharm2018.2/config/scratches/scratch_9.py", line 2, in &lt;module&gt;
    number_two = int(input("Please, enter the second number: "))
ValueError: invalid literal for int() with base 10: 'one'</code></pre> 
  <p>Oh, Lord! We see those red disappointing lines again! Why? Well, because we specified only a <code class="language-python">ZeroDivisionError</code> exception in our try-except block. And here we have a <code class="language-python">ValueError</code> exception, so Python doesn't know how to deal with it in our program.</p> 
  <p>As you know, the built-in exceptions comprise a hierarchical structure, so you can do the following and identify no specific exception:</p> 
  <pre><code class="language-python">except:
    print("An error occurred! Try again.")</code></pre> 
  <p>Thus you'll catch any exception from the list. But it will also work for <code class="language-python">KeyboardInterrupt</code> and other useful exceptions and it's considered to be a bad tone in programming, so it'd be better to use two or more<strong> </strong><code class="language-python">except</code> blocks for different exceptions:</p> 
  <pre><code class="language-python">except ZeroDivisionError:
    print("We achieve it thanks to except ***You can't divide by zero!!")
except ValueError:
    print("You can only enter numbers consisting of digits, not text!!")</code></pre> 
  <p>An <code class="language-python">except</code> clause also may specify multiple exceptions as a <strong>parenthesized tuple</strong>, for example:</p> 
  <pre><code class="language-python">except (ValueError, TypeError):
    print("You can only enter numbers consisting of digits, not text!!")</code></pre> 
  <p>Due to the hierarchical structure, one exception can catch multiple exceptions. For example:</p> 
  <pre><code class="language-python">except ArithmeticError:
    print("I will also catch FloatingPointError, OverflowError, and ZeroDivisionError")</code></pre> 
  <p>Sometimes there can be a situation in which you can't even predict the type of exception in your code. You have no other choice, but to use the most general exception. For that purpose, instead of using pure <code class="language-python">except:</code> statement, like this:</p> 
  <pre><code class="language-python">except:
    # do something</code></pre> 
  <p>you should use <code class="language-python">except Exception</code>:</p> 
  <pre><code class="language-python">except Exception:
    # do something</code></pre> 
  <p><code class="language-python">except Exception</code> contains all Python exceptions but the following three: <code class="language-python">GeneratorExit</code>, <code class="language-python">KeyboardInterrupt</code>, <code class="language-python">SystemExit</code><strong>. </strong>So if you use this structure, you will still be able to finish your program by the means of a keyboard or commands, which cause <code class="language-python">SystemExit</code>.</p> 
  <h5 id="summary" style="text-align: center;">Summary</h5> 
  <ul> 
   <li>To deal with exceptions without terminating your program, Python has the <strong>try-except block.</strong></li> 
   <li>There are two more blocks to expand the possibilities to change the behavior of a program: <code class="language-python">else</code>, which will be executed only if there are no exceptions in try-block, and <code class="language-python">finally</code>, which will be executed at the end of the try-except block whether the exception happened or not.</li> 
   <li>All the exceptions comprise a hierarchical structure, i.e. some exceptions also include other exceptions.</li> 
   <li>If you want to catch all possible exceptions, you should use the <code class="language-python">except Exception</code> construction.</li> 
   <li>Using those means wisely, you can write sustainable and effective code to prevent users' mistakes and to keep your program running even under unexpected circumstances. </li> 
  </ul>
 </body>
</html>
